[build]
publish = "dist/client/"
command = "npm run build"

[functions]
directory = "functions/"
external_node_modules = ["@brillout/vite-plugin-import-build"]

[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200
